### ISSUE TITLE
Updates for API changes?

### ISSUE THREAD

**Issue by strouptl** [graysonc/metascan#1]
@graysonc, hope you are doing well? I was just wondering if you have plans to update your Gem for the api changes (e.g. changing the api url to scan.metascan-online.com...). And if so, I would love to compare notes with you, as I tried doing so myself on my fork, but got the following when I did a filescan: NoMethodError: undefined method `[]' for nil:NilClass.

**Comment by graysonchao** [comment]
Hi Laney,

Haven't looked at this code in a while but I will gladly do so when I have
time. Thanks for letting me know about this :)

G

**Comment by strouptl** [comment]
Awesome! There are not many online file scanning solutions like this (only other one I could find was scanii.com), so I would love to be able to use this gem.

**Comment by strouptl** [comment]
Hey, I just tested out the pull request from @jshak3r and the issue appears to be taken care of. I am still having trouble requiring the gem (which is important for use on PaaS systems like Heroku), but will open a second issue on this.

Thanks!
Laney
